module-name: "odemelistesi"


spring :
  profiles:
    active: dev
  application :
    name : odemelistesi_bcknd
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy

server:
  port: 8085


---
spring:
  config:
    activate:
      on-profile: dev

  # DEVELOPMENT DB
  datasource :
    url : jdbc:postgresql://localhost:5432/bunny
    username : postgres
    password : 5822
    type: org.apache.tomcat.jdbc.pool.DataSource
    tomcat:
      initial-size: 2
      max-wait: 10000
      max-active: 5
      max-idle: 2
      min-idle: 1
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        default_schema: sch_bunny